/* 1. Package e importaciones */
package Analizadores; 
import java_cup.runtime.*;
import java.util.ArrayList;
import java.util.List;



/* 2. Codigo para el parser, variables, metodos */
parser code 
{:
    //Clases, objetos, variables, lista, etc... en sintaxis java
    
    //Creo una lista de tipo String llamada 'resultados', donde guardare cada uno de los resultados analizados
    public List<String> resultados = new ArrayList<String>();
:}  


/* 3. Terminales */
terminal String PTCOMA,LLAVDER,LLAVIZQ;
terminal String DOSPTS,PARDER,PARIZQ,VARIABLE;
terminal String FLECH,NOTACION,EXPOLACA;
terminal String EJEXPRE;
terminal String PR_CONJ;


/* 4. No Terminales */
non terminal ini;
non terminal instrucciones;
non terminal instruccion;
non terminal expresion;
non terminal exppolaca;
non terminal ejempexp;


/* 5. Precedencias */


/* 6. Producciones */

start with ini; 
ini::= LLAVIZQ instrucciones LLAVDER;

instrucciones ::= instrucciones instruccion 
                  | instrucciones error
                  | instruccion
; 

instruccion ::= 
   PR_CONJ DOSPTS expresion:a FLECH expresion:b PTCOMA
    {:
    
        System.out.println("El valor de la Variable es: "+a);
    
        //Inserto en la lista el resultado de la expresión evaluada
         resultados.add("El valor de la Variable es: "+a);
         resultados.add("El valor de la Notacion es: "+b);
    :}

|   expresion:a FLECH exppolaca:b PTCOMA
{:
        System.out.println("El valor de la expresión es: "+a);
    
        //Inserto en la lista el resultado de la expresión evaluada
         resultados.add("El valor de la Expresion es: "+a);
         resultados.add("El valor de la Polaca es: "+b);
    :}
|   expresion:a DOSPTS ejempexp:b PTCOMA
{:
        System.out.println("La expresion de prueba es: "+b);
    
        //Inserto en la lista el resultado de la expresión evaluada
        resultados.add("El valor de la Identificador es: "+a);
        resultados.add("El valor de la Ejemplo es: "+b);
    :}
|   error PTCOMA {:
        //Aqui activa el Panic Mode al encontrar un punto y coma y reporta el error sintactico
    :} 
;


expresion  ::= 
    VARIABLE:a                             {:RESULT=new String(a);:} 
|   NOTACION:a                             {:RESULT=new String(a);:}
;


exppolaca   ::=   
    VARIABLE:a                              {:RESULT=new String(a);:}                         
|   EXPOLACA:a                              {:RESULT=new String(a);:} 
;

ejempexp ::=
    EJEXPRE:a                               {:RESULT=new String(a);:}
;
