
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EXPOLACA = 12;
  public static final int PTCOMA = 2;
  public static final int VARIABLE = 9;
  public static final int EOF = 0;
  public static final int LLAVIZQ = 4;
  public static final int NOTACION = 11;
  public static final int PARIZQ = 8;
  public static final int FLECH = 10;
  public static final int LLAVDER = 3;
  public static final int PR_CONJ = 13;
  public static final int error = 1;
  public static final int DOSPTS = 6;
  public static final int PARDER = 7;
  public static final int EJEXPRE = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "LLAVDER",
  "LLAVIZQ",
  "EJEXPRE",
  "DOSPTS",
  "PARDER",
  "PARIZQ",
  "VARIABLE",
  "FLECH",
  "NOTACION",
  "EXPOLACA",
  "PR_CONJ"
  };
}

